name: CI - Build backend & frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore & Build
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ../api-out

      - name: Upload API artifact
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: api-out

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Upload Web artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: dist
