name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   # match your ASP.NET Core version

      - name: Restore dependencies
        run: dotnet restore ./TaskApi

      - name: Build
        run: dotnet build ./TaskApi --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./TaskApi --no-build --verbosity normal

  frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # match your React version

      - name: Install dependencies
        run: cd client && npm install

      - name: Build React app
        run: cd client && npm run build

      - name: Upload React build artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: client/build
